-- ============================================================
-- Sparkling Designs — Supabase setup script
-- Run this once in: Supabase Dashboard → SQL Editor → New query → Run
-- ============================================================

-- 1. Products table
-- Ids are auto-generated by Postgres for every row, including the ones
-- created by the one-time migration script (scripts/migrate-products.mjs).
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    code text not null,
    category text not null,
    description text default '',
    material text default '',
    colors text[] default '{}',
    sizes text[] default '{}',
    images text[] default '{}',
    price text default '',
    featured boolean default false,
    new_arrival boolean default false,
    best_seller boolean default false,
    newly_added boolean default false,
    customization_available boolean default false,
    rating numeric default 5.0,
    created_at timestamptz default now()
);

-- Helpful index for filtering/sorting by category and creation date
create index if not exists products_category_idx on public.products (category);
create index if not exists products_created_at_idx on public.products (created_at desc);

-- 2. Row Level Security
-- The site is public (anyone can browse the catalog), and the Admin area is
-- protected by the app's own hardcoded login screen rather than Supabase auth.
-- We therefore allow the "anon" key to read AND write — this matches the
-- current app design (no real backend auth yet). If you later add real
-- Supabase Auth for the admin, tighten the write policies to check auth.uid().

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
    on public.products for select
    using (true);

drop policy if exists "Public can insert products" on public.products;
create policy "Public can insert products"
    on public.products for insert
    with check (true);

drop policy if exists "Public can update products" on public.products;
create policy "Public can update products"
    on public.products for update
    using (true);

drop policy if exists "Public can delete products" on public.products;
create policy "Public can delete products"
    on public.products for delete
    using (true);

-- 3. Storage bucket for product images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Allow public read of product images
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
    on storage.objects for select
    using (bucket_id = 'product-images');

-- Allow uploads/updates/deletes to the product-images bucket
-- (same reasoning as above: admin auth is handled in the app, not Supabase)
drop policy if exists "Public can upload product images" on storage.objects;
create policy "Public can upload product images"
    on storage.objects for insert
    with check (bucket_id = 'product-images');

drop policy if exists "Public can update product images" on storage.objects;
create policy "Public can update product images"
    on storage.objects for update
    using (bucket_id = 'product-images');

drop policy if exists "Public can delete product images" on storage.objects;
create policy "Public can delete product images"
    on storage.objects for delete
    using (bucket_id = 'product-images');
